# Generated by Django 5.1.2 on 2024-10-21 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oradbaleApp', '0005_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderItem',
        ),
    ]
