# Generated by Django 5.1.2 on 2024-10-21 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oradbaleApp', '0006_remove_order_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='x',
        ),
    ]
