# Generated by Django 5.1.2 on 2024-10-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oradbaleApp', '0007_remove_orderitem_x'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='selected_options',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
