# Generated by Django 5.1.2 on 2024-10-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oradbaleApp', '0010_remove_product_options_options_itemoptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemoptions',
            name='extra_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
