# Generated by Django 5.1.2 on 2024-10-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oradbaleApp', '0011_itemoptions_extra_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ItemOptions',
            new_name='ProductOptions',
        ),
    ]
