# Generated by Django 5.1.2 on 2024-10-25 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oradbaleApp', '0012_rename_itemoptions_productoptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='oradbaleApp.product'),
        ),
        migrations.AlterField(
            model_name='productoptions',
            name='options',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_options', to='oradbaleApp.options'),
        ),
    ]
