// Authentication action types
export const AUTH_LOGIN_REQUEST = "AUTH_LOGIN_REQUEST";
export const AUTH_LOGIN_SUCCESS = "AUTH_LOGIN_SUCCESS";
export const AUTH_LOGIN_FAILURE = "AUTH_LOGIN_FAILURE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_USER = "SET_AUTH_USER";

export const ADD_ITEM = "ADD_ITEM";
export const REMOVE_ITEM = "REMOVE_ITEM";

export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const CREATE_PRODUCT_ERROR = "CREATE_PRODUCT_ERROR";
export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCH_PRODUCTS_LOADING = "FETCH_PRODUCTS_LOADING";
export const FETCH_PRODUCTS_ERROR = "FETCH_PRODUCTS_ERROR";
export const FETCH_PRODUCT_DETAIL_LOADING = "FETCH_PRODUCT_DETAIL_LOADING";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const FETCH_PRODUCT_DETAIL_ERROR = "FETCH_PRODUCT_DETAIL_ERROR";

export const CREATE_PAYMENT = "CREATE_PAYMENT";
export const FETCH_PAYMENT_METHODS = "FETCH_PAYMENT_METHODS";
export const FETCH_PAYMENT_METHODS_LOADING = "FETCH_PAYMENT_METHODS_LOADING";
export const FETCH_PAYMENT_METHODS_ERROR = "FETCH_PAYMENT_METHODS_ERROR";
export const CREATE_PAYMENT_SUCCESS = "CREATE_PAYMENT_SUCCESS";
export const CREATE_PAYMENT_FAILURE = "CREATE_PAYMENT_FAILURE";
export const CREATE_PAYMENT_LOADING = "CREATE_PAYMENT_LOADING";
export const CREATE_PAYMENT_ERROR = "CREATE_PAYMENT_ERROR";

export const CREATE_ORDER = "CREATE_ORDER";

export const FETCH_ORDERS = "FETCH_ORDERS";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";
export const FETCH_ORDER_DETAIL = "FETCH_ORDER_DETAIL";
export const FETCH_ORDER_DETAIL_ERROR = "FETCH_ORDER_DETAIL_ERROR";
export const FETCH_ORDER_DETAIL_LOADING = "FETCH_ORDER_DETAIL_LOADING";
export const FETCH_ORDERS_LOADING = "FETCH_ORDERS_LOADING";
export const FETCH_ORDER_DETAIL_SUCCESS = "FETCH_ORDER_DETAIL_SUCCESS";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_LOADING = "CREATE_ORDER_LOADING";
export const CREATE_ORDER_FAILURE = "CREATE_ORDER_FAILURE";
export const UPDATE_ORDER = "UPDATE_ORDER";
